blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/7k7kzSDwpn
    about: Ask questions and get help on our Discord server.
  - name: Cheetah Documentation
    url: https://cheetah-accelerator.readthedocs.io/
    about: Read the official Cheetah documentation and tutorials.
