name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install black and isort
        run: pip install black isort

      - name: Run black
        run: black . --check --verbose --diff --color --exclude="/*.ipynb/"

      - name: Run isort
        run: isort . --check --diff --profile black
