name: Publish Python 🐍 distribution 📦 to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/cheetah-accelerator

    # IMPORTANT: This permission is required for Trusted Publishing (OIDC)
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: pip install build

      - name: Build a binary wheel and a source tarball
        run: build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
